### ISSUE TITLE
400 Client Error: Bad Request for path: /customers:listAccessibleCustomers

### ISSUE THREAD

**Issue by ivanblagdan** [AutoIDM/tap-googleads#42]
Hi,

First of all, thanks for the tap! I've been trying to set it up and bumped into an issue fairly early on. I'm seeing `singer_sdk.exceptions.FatalAPIError: 400 Client Error: Bad Request for path: /customers:listAccessibleCustomers`. 
In the API console, I can see the `google.ads.googleads.v8.services.CustomerService.ListAccessibleCustomers` requests erroring out at a 100% rate. 

Mind you, I haven't had an AdWords tap setup previously, this is my first attempt and right now it seems you can't even enable the AdWords endpoints through the console anymore.

Below is a relevant section of the run, happy to provide more details.
```
2022-04-06T17:31:33.245485Z [info     ] time=2022-04-06 17:31:33 name=tap-googleads level=INFO message=tap-googleads v0.0.8, Meltano SDK v0.3.17) cmd_type=extractor job_id=2022-04-06T173122--tap-googleads--target-redshift name=tap-googleads run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:31:33.250424Z [info     ] time=2022-04-06 17:31:33 name=tap-googleads level=INFO message=Skipping parse of env var settings... cmd_type=extractor job_id=2022-04-06T173122--tap-googleads--target-redshift name=tap-googleads run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:31:33.252183Z [info     ] time=2022-04-06 17:31:33 name=tap-googleads level=INFO message=Config validation passed with 0 errors and 0 warnings. cmd_type=extractor job_id=2022-04-06T173122--tap-googleads--target-redshift name=tap-googleads run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:31:33.259158Z [info     ] time=2022-04-06 17:31:33 name=root level=INFO message=Operator '__else__=None' was not found. Unmapped streams will be included in output. cmd_type=extractor job_id=2022-04-06T173122--tap-googleads--target-redshift name=tap-googleads run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:31:33.298158Z [info     ] time=2022-04-06 17:31:33 name=tap-googleads level=INFO message=Added 'campaign' as child stream to 'customer_hierarchystream' cmd_type=extractor job_id=2022-04-06T173122--tap-googleads--target-redshift name=tap-googleads run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:31:33.299411Z [info     ] time=2022-04-06 17:31:33 name=tap-googleads level=INFO message=Added 'adgroups' as child stream to 'customer_hierarchystream' cmd_type=extractor job_id=2022-04-06T173122--tap-googleads--target-redshift name=tap-googleads run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:31:33.300673Z [info     ] time=2022-04-06 17:31:33 name=tap-googleads level=INFO message=Added 'adgroupsperformance' as child stream to 'customer_hierarchystream' cmd_type=extractor job_id=2022-04-06T173122--tap-googleads--target-redshift name=tap-googleads run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:31:33.301823Z [info     ] time=2022-04-06 17:31:33 name=tap-googleads level=INFO message=Added 'customer_hierarchystream' as child stream to 'accessible_customers' cmd_type=extractor job_id=2022-04-06T173122--tap-googleads--target-redshift name=tap-googleads run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:31:33.304356Z [info     ] time=2022-04-06 17:31:33 name=tap-googleads level=INFO message=Added 'campaign_performance' as child stream to 'customer_hierarchystream' cmd_type=extractor job_id=2022-04-06T173122--tap-googleads--target-redshift name=tap-googleads run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:31:33.305435Z [info     ] time=2022-04-06 17:31:33 name=tap-googleads level=INFO message=Added 'campaign_performance_by_age_range_and_device' as child stream to 'customer_hierarchystream' cmd_type=extractor job_id=2022-04-06T173122--tap-googleads--target-redshift name=tap-googleads run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:31:33.306853Z [info     ] time=2022-04-06 17:31:33 name=tap-googleads level=INFO message=Added 'campaign_performance_by_gender_and_device' as child stream to 'customer_hierarchystream' cmd_type=extractor job_id=2022-04-06T173122--tap-googleads--target-redshift name=tap-googleads run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:31:33.309275Z [info     ] time=2022-04-06 17:31:33 name=tap-googleads level=INFO message=Added 'campaign_performance_by_location' as child stream to 'customer_hierarchystream' cmd_type=extractor job_id=2022-04-06T173122--tap-googleads--target-redshift name=tap-googleads run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:31:33.312789Z [info     ] time=2022-04-06 17:31:33 name=tap-googleads level=INFO message=Added 'conversion_by_location' as child stream to 'customer_hierarchystream' cmd_type=extractor job_id=2022-04-06T173122--tap-googleads--target-redshift name=tap-googleads run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:31:33.314891Z [info     ] time=2022-04-06 17:31:33 name=tap-googleads level=INFO message=Added 'campaign_label' as child stream to 'customer_hierarchystream' cmd_type=extractor job_id=2022-04-06T173122--tap-googleads--target-redshift name=tap-googleads run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:31:33.316696Z [info     ] time=2022-04-06 17:31:33 name=tap-googleads level=INFO message=Beginning full_table sync of 'accessible_customers'... cmd_type=extractor job_id=2022-04-06T173122--tap-googleads--target-redshift name=tap-googleads run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:31:33.319023Z [info     ] time=2022-04-06 17:31:33 name=tap-googleads level=INFO message=Tap has custom mapper. Using 1 provided map(s). cmd_type=extractor job_id=2022-04-06T173122--tap-googleads--target-redshift name=tap-googleads run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:31:33.320395Z [debug    ] {"type": "SCHEMA", "stream": "accessible_customers", "schema": {"properties": {"resourceNames": {"items": {"type": ["string"]}, "type": ["array", "null"]}}, "type": "object"}, "key_properties": []} cmd_type=extractor job_id=2022-04-06T173122--tap-googleads--target-redshift name=tap-googleads (out) run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stdout
2022-04-06T17:31:33.490997Z [info     ] time=2022-04-06 17:31:33 name=tap-googleads level=INFO message=OAuth authorization attempt was successful. cmd_type=extractor job_id=2022-04-06T173122--tap-googleads--target-redshift name=tap-googleads run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:31:33.733141Z [info     ] time=2022-04-06 17:31:33 name=tap-googleads level=INFO message=INFO METRIC: {'type': 'timer', 'metric': 'http_request_duration', 'value': 0.239989, 'tags': {'endpoint': '/customers:listAccessibleCustomers', 'http_status_code': 400, 'status': 'failed', 'url': '/v8/customers:listAccessibleCustomers'}} cmd_type=extractor job_id=2022-04-06T173122--tap-googleads--target-redshift name=tap-googleads run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:31:33.772301Z [info     ] Traceback (most recent call last): cmd_type=extractor job_id=2022-04-06T173122--tap-googleads--target-redshift name=tap-googleads run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:31:33.774294Z [info     ]   File "/project/.meltano/extractors/tap-googleads/venv/bin/tap-googleads", line 8, in <module> cmd_type=extractor job_id=2022-04-06T173122--tap-googleads--target-redshift name=tap-googleads run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:31:33.775389Z [info     ]     sys.exit(TapGoogleAds.cli()) cmd_type=extractor job_id=2022-04-06T173122--tap-googleads--target-redshift name=tap-googleads run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:31:33.777227Z [info     ]   File "/project/.meltano/extractors/tap-googleads/venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__ cmd_type=extractor job_id=2022-04-06T173122--tap-googleads--target-redshift name=tap-googleads run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:31:33.779541Z [info     ]     return self.main(*args, **kwargs) cmd_type=extractor job_id=2022-04-06T173122--tap-googleads--target-redshift name=tap-googleads run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:31:33.782108Z [info     ]   File "/project/.meltano/extractors/tap-googleads/venv/lib/python3.8/site-packages/click/core.py", line 1055, in main cmd_type=extractor job_id=2022-04-06T173122--tap-googleads--target-redshift name=tap-googleads run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:31:33.784585Z [info     ]     rv = self.invoke(ctx)      cmd_type=extractor job_id=2022-04-06T173122--tap-googleads--target-redshift name=tap-googleads run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:31:33.786501Z [info     ]   File "/project/.meltano/extractors/tap-googleads/venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke cmd_type=extractor job_id=2022-04-06T173122--tap-googleads--target-redshift name=tap-googleads run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:31:33.788280Z [info     ]     return ctx.invoke(self.callback, **ctx.params) cmd_type=extractor job_id=2022-04-06T173122--tap-googleads--target-redshift name=tap-googleads run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:31:33.789610Z [info     ]   File "/project/.meltano/extractors/tap-googleads/venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke cmd_type=extractor job_id=2022-04-06T173122--tap-googleads--target-redshift name=tap-googleads run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:31:33.791425Z [info     ]     return __callback(*args, **kwargs) cmd_type=extractor job_id=2022-04-06T173122--tap-googleads--target-redshift name=tap-googleads run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:31:33.792669Z [info     ]   File "/project/.meltano/extractors/tap-googleads/venv/lib/python3.8/site-packages/singer_sdk/tap_base.py", line 476, in cli cmd_type=extractor job_id=2022-04-06T173122--tap-googleads--target-redshift name=tap-googleads run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:31:33.794325Z [info     ]     tap.sync_all()             cmd_type=extractor job_id=2022-04-06T173122--tap-googleads--target-redshift name=tap-googleads run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:31:33.796105Z [info     ]   File "/project/.meltano/extractors/tap-googleads/venv/lib/python3.8/site-packages/singer_sdk/tap_base.py", line 345, in sync_all cmd_type=extractor job_id=2022-04-06T173122--tap-googleads--target-redshift name=tap-googleads run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:31:33.797660Z [info     ]     stream.sync()              cmd_type=extractor job_id=2022-04-06T173122--tap-googleads--target-redshift name=tap-googleads run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:31:33.799520Z [info     ]   File "/project/.meltano/extractors/tap-googleads/venv/lib/python3.8/site-packages/singer_sdk/streams/core.py", line 1010, in sync cmd_type=extractor job_id=2022-04-06T173122--tap-googleads--target-redshift name=tap-googleads run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:31:33.802393Z [info     ]     self._sync_records(context) cmd_type=extractor job_id=2022-04-06T173122--tap-googleads--target-redshift name=tap-googleads run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:31:33.803761Z [info     ]   File "/project/.meltano/extractors/tap-googleads/venv/lib/python3.8/site-packages/singer_sdk/streams/core.py", line 937, in _sync_records cmd_type=extractor job_id=2022-04-06T173122--tap-googleads--target-redshift name=tap-googleads run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:31:33.805264Z [info     ]     for record_result in self.get_records(current_context): cmd_type=extractor job_id=2022-04-06T173122--tap-googleads--target-redshift name=tap-googleads run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:31:33.806816Z [info     ]   File "/project/.meltano/extractors/tap-googleads/venv/lib/python3.8/site-packages/tap_googleads/client.py", line 123, in get_records cmd_type=extractor job_id=2022-04-06T173122--tap-googleads--target-redshift name=tap-googleads run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:31:33.808242Z [info     ]     for record in self.request_records(context): cmd_type=extractor job_id=2022-04-06T173122--tap-googleads--target-redshift name=tap-googleads run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:31:33.809775Z [info     ]   File "/project/.meltano/extractors/tap-googleads/venv/lib/python3.8/site-packages/singer_sdk/streams/rest.py", line 293, in request_records cmd_type=extractor job_id=2022-04-06T173122--tap-googleads--target-redshift name=tap-googleads run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:31:33.811444Z [info     ]     resp = decorated_request(prepared_request, context) cmd_type=extractor job_id=2022-04-06T173122--tap-googleads--target-redshift name=tap-googleads run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:31:33.813973Z [info     ]   File "/project/.meltano/extractors/tap-googleads/venv/lib/python3.8/site-packages/backoff/_sync.py", line 94, in retry cmd_type=extractor job_id=2022-04-06T173122--tap-googleads--target-redshift name=tap-googleads run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:31:33.815616Z [info     ]     ret = target(*args, **kwargs) cmd_type=extractor job_id=2022-04-06T173122--tap-googleads--target-redshift name=tap-googleads run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:31:33.817097Z [info     ]   File "/project/.meltano/extractors/tap-googleads/venv/lib/python3.8/site-packages/singer_sdk/streams/rest.py", line 209, in _request cmd_type=extractor job_id=2022-04-06T173122--tap-googleads--target-redshift name=tap-googleads run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:31:33.819078Z [info     ]     self.validate_response(response) cmd_type=extractor job_id=2022-04-06T173122--tap-googleads--target-redshift name=tap-googleads run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:31:33.820978Z [info     ]   File "/project/.meltano/extractors/tap-googleads/venv/lib/python3.8/site-packages/tap_googleads/client.py", line 102, in validate_response cmd_type=extractor job_id=2022-04-06T173122--tap-googleads--target-redshift name=tap-googleads run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:31:33.822722Z [info     ]     raise FatalAPIError(msg)   cmd_type=extractor job_id=2022-04-06T173122--tap-googleads--target-redshift name=tap-googleads run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:31:33.824592Z [info     ] singer_sdk.exceptions.FatalAPIError: 400 Client Error: Bad Request for path: /customers:listAccessibleCustomers cmd_type=extractor job_id=2022-04-06T173122--tap-googleads--target-redshift name=tap-googleads run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:31:33.919382Z [info     ] time=2022-04-06 17:31:33 name=target_redshift level=INFO message=Getting catalog objects from table cache... cmd_type=loader job_id=2022-04-06T173122--tap-googleads--target-redshift name=target-redshift run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:32:50.034463Z [info     ] Traceback (most recent call last): cmd_type=loader job_id=2022-04-06T173122--tap-googleads--target-redshift name=target-redshift run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:32:50.039760Z [info     ]   File "/project/.meltano/loaders/target-redshift/venv/bin/target-redshift", line 8, in <module> cmd_type=loader job_id=2022-04-06T173122--tap-googleads--target-redshift name=target-redshift run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:32:50.041302Z [info     ]     sys.exit(main())           cmd_type=loader job_id=2022-04-06T173122--tap-googleads--target-redshift name=target-redshift run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:32:50.042714Z [info     ]   File "/project/.meltano/loaders/target-redshift/venv/lib/python3.8/site-packages/target_redshift/__init__.py", line 444, in main cmd_type=loader job_id=2022-04-06T173122--tap-googleads--target-redshift name=target-redshift run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:32:50.044336Z [info     ]     table_cache = load_table_cache(config) cmd_type=loader job_id=2022-04-06T173122--tap-googleads--target-redshift name=target-redshift run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:32:50.045726Z [info     ]   File "/project/.meltano/loaders/target-redshift/venv/lib/python3.8/site-packages/target_redshift/__init__.py", line 108, in load_table_cache cmd_type=loader job_id=2022-04-06T173122--tap-googleads--target-redshift name=target-redshift run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:32:50.047039Z [info     ]     table_cache = db.get_table_columns( cmd_type=loader job_id=2022-04-06T173122--tap-googleads--target-redshift name=target-redshift run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:32:50.048219Z [info     ]   File "/project/.meltano/loaders/target-redshift/venv/lib/python3.8/site-packages/target_redshift/db_sync.py", line 632, in get_table_columns cmd_type=loader job_id=2022-04-06T173122--tap-googleads--target-redshift name=target-redshift run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:32:50.049778Z [info     ]     return self.query(sql)     cmd_type=loader job_id=2022-04-06T173122--tap-googleads--target-redshift name=target-redshift run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:32:50.051377Z [info     ]   File "/project/.meltano/loaders/target-redshift/venv/lib/python3.8/site-packages/target_redshift/db_sync.py", line 333, in query cmd_type=loader job_id=2022-04-06T173122--tap-googleads--target-redshift name=target-redshift run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:32:50.052934Z [info     ]     with self.open_connection() as connection: cmd_type=loader job_id=2022-04-06T173122--tap-googleads--target-redshift name=target-redshift run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:32:50.054903Z [info     ]   File "/project/.meltano/loaders/target-redshift/venv/lib/python3.8/site-packages/target_redshift/db_sync.py", line 329, in open_connection cmd_type=loader job_id=2022-04-06T173122--tap-googleads--target-redshift name=target-redshift run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:32:50.056490Z [info     ]     return psycopg2.connect(conn_string) cmd_type=loader job_id=2022-04-06T173122--tap-googleads--target-redshift name=target-redshift run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:32:50.057939Z [info     ]   File "/project/.meltano/loaders/target-redshift/venv/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect cmd_type=loader job_id=2022-04-06T173122--tap-googleads--target-redshift name=target-redshift run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:32:50.059401Z [info     ]     conn = _connect(dsn, connection_factory=connection_factory, **kwasync) cmd_type=loader job_id=2022-04-06T173122--tap-googleads--target-redshift name=target-redshift run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:32:50.062110Z [info     ] psycopg2.OperationalError: could not connect to server: Connection refused cmd_type=loader job_id=2022-04-06T173122--tap-googleads--target-redshift name=target-redshift run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:32:50.063313Z [info     ] 	Is the server running on host "reportiv.chy9qh3mxgx9.us-east-1.redshift.amazonaws.com" (52.0.140.187) and accepting cmd_type=loader job_id=2022-04-06T173122--tap-googleads--target-redshift name=target-redshift run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:32:50.064663Z [info     ] 	TCP/IP connections on port 5439? cmd_type=loader job_id=2022-04-06T173122--tap-googleads--target-redshift name=target-redshift run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:32:50.066115Z [info     ]                                cmd_type=loader job_id=2022-04-06T173122--tap-googleads--target-redshift name=target-redshift run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7 stdio=stderr
2022-04-06T17:32:50.211361Z [debug    ] Deleted configuration at /project/.meltano/run/elt/2022-04-06T173122--tap-googleads--target-redshift/aa915d62-7ead-4578-9e29-6481ff6c22f7/target.d87709ee-3f0d-4e09-a13b-056579b41edf.config.json
2022-04-06T17:32:50.215714Z [debug    ] Deleted configuration at /project/.meltano/run/elt/2022-04-06T173122--tap-googleads--target-redshift/aa915d62-7ead-4578-9e29-6481ff6c22f7/tap.42ea2ef2-7198-4888-8e81-172376955ec1.config.json
2022-04-06T17:32:50.216957Z [error    ] Extraction failed              code=1 job_id=2022-04-06T173122--tap-googleads--target-redshift message=singer_sdk.exceptions.FatalAPIError: 400 Client Error: Bad Request for path: /customers:listAccessibleCustomers name=meltano run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7
2022-04-06T17:32:50.218226Z [error    ] Loading failed                 code=1 job_id=2022-04-06T173122--tap-googleads--target-redshift message=(see above) name=meltano run_id=aa915d62-7ead-4578-9e29-6481ff6c22f7
2022-04-06T17:32:50.223251Z [debug    ] ELT could not be completed: Extractor and loader failed.
```

**Comment by visch** [comment]
Thank you for the issue! 

I"ll get some debugging added and have you re-run give me a few

**Comment by visch** [comment]
Released https://github.com/AutoIDM/tap-googleads/releases/tag/v0.0.9 for you , can you give that a shot @ivanblagdan that should give us better logging information if we're lucky!

**Comment by ivanblagdan** [comment]
Hey @visch !
Thanks for the prompt response. I'm getting back proper feedback from the logs now so i was able to work through a bunch of mistakes i made with the config.

Here's what the error looked like:
```
2022-04-07T15:28:12.472880Z [info     ] singer_sdk.exceptions.FatalAPIError: 403 Client Error: Forbidden for path: /customers/{client_id}/googleAds:search?pageSize=10000&query= cmd_type=extractor job_id=2022-04-07T152802--tap-googleads--target-redshift name=tap-googleads run_id=5b655e9e-6647-4289-aaaf-f7154b017b2c stdio=stderr
2022-04-07T15:28:12.474477Z [info     ] 	        SELECT customer_client.client_customer cmd_type=extractor job_id=2022-04-07T152802--tap-googleads--target-redshift name=tap-googleads run_id=5b655e9e-6647-4289-aaaf-f7154b017b2c stdio=stderr
2022-04-07T15:28:12.476989Z [info     ]                  , customer_client.level cmd_type=extractor job_id=2022-04-07T152802--tap-googleads--target-redshift name=tap-googleads run_id=5b655e9e-6647-4289-aaaf-f7154b017b2c stdio=stderr
2022-04-07T15:28:12.478403Z [info     ]                  , customer_client.manager cmd_type=extractor job_id=2022-04-07T152802--tap-googleads--target-redshift name=tap-googleads run_id=5b655e9e-6647-4289-aaaf-f7154b017b2c stdio=stderr
2022-04-07T15:28:12.479626Z [info     ]                  , customer_client.descriptive_name cmd_type=extractor job_id=2022-04-07T152802--tap-googleads--target-redshift name=tap-googleads run_id=5b655e9e-6647-4289-aaaf-f7154b017b2c stdio=stderr
2022-04-07T15:28:12.481182Z [info     ]                  , customer_client.currency_code cmd_type=extractor job_id=2022-04-07T152802--tap-googleads--target-redshift name=tap-googleads run_id=5b655e9e-6647-4289-aaaf-f7154b017b2c stdio=stderr
2022-04-07T15:28:12.483280Z [info     ]                  , customer_client.time_zone cmd_type=extractor job_id=2022-04-07T152802--tap-googleads--target-redshift name=tap-googleads run_id=5b655e9e-6647-4289-aaaf-f7154b017b2c stdio=stderr
2022-04-07T15:28:12.485052Z [info     ]                  , customer_client.id cmd_type=extractor job_id=2022-04-07T152802--tap-googleads--target-redshift name=tap-googleads run_id=5b655e9e-6647-4289-aaaf-f7154b017b2c stdio=stderr
2022-04-07T15:28:12.486479Z [info     ]             FROM customer_client cmd_type=extractor job_id=2022-04-07T152802--tap-googleads--target-redshift name=tap-googleads run_id=5b655e9e-6647-4289-aaaf-f7154b017b2c stdio=stderr
2022-04-07T15:28:12.488101Z [info     ]             WHERE customer_client.level <= 1 cmd_type=extractor job_id=2022-04-07T152802--tap-googleads--target-redshift name=tap-googleads run_id=5b655e9e-6647-4289-aaaf-f7154b017b2c stdio=stderr
2022-04-07T15:28:12.489447Z [info     ]             .response.json() {'error': {'code': 403, 'message': 'The caller does not have permission', 'status': 'PERMISSION_DENIED', 'details': [{'@type': 'type.googleapis.com/google.ads.googleads.v8.errors.GoogleAdsFailure', 'errors': [{'errorCode': {'authorizationError': 'USER_PERMISSION_DENIED'}, 'message': "User doesn't have permission to access customer. Note: If you're accessing a client customer, the manager's customer id must be set in the 'login-customer-id' header. See https://developers.google.com/google-ads/api/docs/concepts/call-structure#cid"}], 'requestId': 'CnKvhhhbPCp5gye_ZJVDUw'}]}}: cmd_type=extractor job_id=2022-04-07T152802--tap-googleads--target-redshift name=tap-googleads run_id=5b655e9e-6647-4289-aaaf-f7154b017b2c stdio=stderr
```
